dashboard/urls.py
from django.urls import path
from django.views.generic import TemplateView
from .views import *

app_name = 'dashboard'

urlpatterns = [
    path('', TemplateView.as_view(template_name='dashboard/index.html')),
    path('lista-curs/', lista_curso, name='lista_curso'),
]

sistema_inscripciones/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('website.urls')),
    path('usuarios/', include('usuarios.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('dashboard/', include('dashboard.urls')),
]

usuarios/urls.py
from django.urls import path
from .views import *

app_name = 'usuarios'

urlpatterns = [
    path('perfil_alumno', perfil_alumno, name='perfil_alumno')
]

website/urls.py
from django.urls import path
from .views import *

# from django.views.generic import TemplateView

app_name = 'website'

urlpatterns = [
    path('', index_website, name='index'),
    path('detalle-curso/<int:pk>/', detalle_curso, name='detalle_curso'),
    path('registro/', registro_alumno, name='registro_alumno'),
    path('inscripcion/', inscripcion_alumno, name='inscripcion_curso'),
    path('quienes-somos/', TemplateView.as_view(template_name='website/quienes_somos.html'), name='quienes_somos'),
    path('contacto/', TemplateView.as_view(template_name='website/contacto.html'), name='contacto'),
    # path('inscripcion', TemplateView.as_view(template_name='website/inscripcion_curso.html'), name='inscripcion_curso'),
]

cursos/models.py
from django.db import models

# Create your models here.

dashboard/models.py
from django.db import models

# Create your models here.

usuarios/models.py
from django.db import models

# Create your models here.

website/models.py
from django.db import models

# Create your models here.

website/forms.py
from django import forms


class InscripcionAlumnoCursoForm(forms.Form):
    comprobante_domicilio = forms.FileField()
    curp = forms.FileField()
    identificacion_oficial = forms.FileField()
    comprobante_pago = forms.FileField()
    comprobante_estudios = forms.FileField()
    acta_nacimiento = forms.FileField()

cursos/views.py
from django.shortcuts import render

# Create your views here.

dashboard/views.py
from django.shortcuts import render

# Create your views here.
def lista_curso(request):
    return render(request, 'dashboard/cursos/lista_cursos.html')

usuarios/views.py
from django.shortcuts import render


# Create your views here.
def perfil_alumno(request):
    return render(request, 'usuarios/perfil_alumno.html')

website/views.py
from django.contrib.auth.forms import UserCreationForm
from django.shortcuts import render, redirect
from django.views.generic import TemplateView

from website.forms import InscripcionAlumnoCursoForm


# Create your views here.
def index_website(request):
    return render(request, 'website/index.html')


def detalle_curso(request, pk):
    return render(request, 'website/detalle_curso.html')


def registro_alumno(request):
    form = UserCreationForm()

    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('login')

    context = {'form': form}
    return render(request, 'registration/registro_alumno.html', context)


def inscripcion_alumno(request):
    form = InscripcionAlumnoCursoForm()
    if request.method == 'POST':
        print('hacer el proceso de sincripcion')

    return render(request, 'website/inscripcion_curso.html', {'form': form})


class inscripcionAlumnoView(TemplateView):
    template_name = 'website/inscripcion_curso.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        form = InscripcionAlumnoCursoForm()
        context['form'] = form
        return context

dashboard/templates/dashboard/base_dashboard.html
{% load static %}
<!doctype html>
<html lang="es">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Sitio Administrativo">
    <meta name="author" content="Dante">
    <meta name="generator" content="Hugo 0.104.2">
    <title>
        {% block title_tab %}

        {% endblock %}
    </title>

    <link rel="canonical" href="https://getbootstrap.com/docs/5.2/examples/dashboard/">


    <link href="{% static 'dashboard/assets/dist/css/bootstrap.min.css' %}" rel="stylesheet">

    <style>
        .bd-placeholder-img {
            font-size: 1.125rem;
            text-anchor: middle;
            -webkit-user-select: none;
            -moz-user-select: none;
            user-select: none;
        }

        @media (min-width: 768px) {
            .bd-placeholder-img-lg {
                font-size: 3.5rem;
            }
        }

        .b-example-divider {
            height: 3rem;
            background-color: rgba(0, 0, 0, .1);
            border: solid rgba(0, 0, 0, .15);
            border-width: 1px 0;
            box-shadow: inset 0 .5em 1.5em rgba(0, 0, 0, .1), inset 0 .125em .5em rgba(0, 0, 0, .15);
        }

        .b-example-vr {
            flex-shrink: 0;
            width: 1.5rem;
            height: 100vh;
        }

        .bi {
            vertical-align: -.125em;
            fill: currentColor;
        }

        .nav-scroller {
            position: relative;
            z-index: 2;
            height: 2.75rem;
            overflow-y: hidden;
        }

        .nav-scroller .nav {
            display: flex;
            flex-wrap: nowrap;
            padding-bottom: 1rem;
            margin-top: -1px;
            overflow-x: auto;
            text-align: center;
            white-space: nowrap;
            -webkit-overflow-scrolling: touch;
        }
    </style>

    {% block extra_css %}

    {% endblock %}

    <!-- Custom styles for this template -->
    <link href="{% static 'dashboard/dashboard.css' %}" rel="stylesheet">
</head>
<body>
{% include 'dashboard/navbar.html' %}
<div class="container-fluid">
    <div class="row">
        {% include 'dashboard/sidebar.html' %}
        <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
            {% block contenido %}

            {% endblock %}
        </main>
    </div>
</div>

<script src="{% static 'dashboard/assets/dist/js/bootstrap.bundle.min.js' %}"></script>

<script src="https://cdn.jsdelivr.net/npm/feather-icons@4.28.0/dist/feather.min.js"
        integrity="sha384-uO3SXW5IuS1ZpFPKugNNWqTZRRglnUJK6UAZ/gxOX80nxEkN9NcGZTftn6RzhGWE"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.4/dist/Chart.min.js"
        integrity="sha384-zNy6FEbO50N+Cg5wap8IKA4M/ZnLJgzc6w2NqACZaK0u0FXfOWRRJOnQtpZun8ha"
        crossorigin="anonymous"></script>
<script src="{% static 'dashboard/dashboard.js' %}"></script>
{% block extra_js %}

{% endblock %}
</body>
</html>

dashboard/templates/dashboard/cursos/lista_cursos.html
{% extends 'dashboard/base_dashboard.html' %}

{% block contenido %}
    <div class="row">
        <div class="col"$>
            <h1>cursos</h1>
            <a href="#">Nuevo Curso</a>
            <table class="table">
                <thead>
                    <tr>
                        <th>#</th>
                        <th>Curso</th>
                        <th>Estatus</th>
                        <th>Opciones</th>
                    </tr>
                </thead>
                <tbody>

                </tbody>
            </table>
        </div>
    </div>
{% endblock %}

dashboard/templates/dashboard/index.html
{% extends 'dashboard/base_dashboard.html' %}

{% block contenido %}
    <h1>index</h1>
{% endblock %}

dashboard/templates/dashboard/navbar.html
<header class="navbar navbar-dark sticky-top bg-dark flex-md-nowrap p-0 shadow">
    <a class="navbar-brand col-md-3 col-lg-2 me-0 px-3 fs-6" href="#">Cursos</a>
    <button class="navbar-toggler position-absolute d-md-none collapsed" type="button" data-bs-toggle="collapse"
            data-bs-target="#sidebarMenu" aria-controls="sidebarMenu" aria-expanded="false"
            aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <input class="form-control form-control-dark w-100 rounded-0 border-0" type="text" placeholder="Buscar"
           aria-label="Search">
    <div class="navbar-nav">
        <div class="nav-item text-nowrap">
            <a class="nav-link px-3" href="#">Salir</a>
        </div>
    </div>
</header>

dashboard/templates/dashboard/sidebar.html
<nav id="sidebarMenu" class="col-md-3 col-lg-2 d-md-block bg-light sidebar collapse">
    <div class="position-sticky pt-3 sidebar-sticky">
        <ul class="nav flex-column">
            <li class="nav-item">
                <a class="nav-link" aria-current="page" href="#">
                    <span data-feather="home" class="align-text-bottom"></span>
                    Inicio
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'dashboard:lista_curso' %}">
                    <span data-feather="file" class="align-text-bottom"></span>
                    Cursos
                </a>
            </li>
        </ul>

{#        <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted text-uppercase">#}
{#            <span>Saved reports</span>#}
{#            <a class="link-secondary" href="#" aria-label="Add a new report">#}
{#                <span data-feather="plus-circle" class="align-text-bottom"></span>#}
{#            </a>#}
{#        </h6>#}
{#        <ul class="nav flex-column mb-2">#}
{#            <li class="nav-item">#}
{#                <a class="nav-link" href="#">#}
{#                    <span data-feather="file-text" class="align-text-bottom"></span>#}
{#                    Current month#}
{#                </a>#}
{#            </li>#}
{#        </ul>#}
    </div>
</nav>

templates/base.html
{% load static %}
<!doctype html>
<html lang="es">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>
        {% block tittle_tab %}
        {% endblock %}
    </title>
    <link href="{% static 'bs522/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'fa/all.min.css' %}" rel="stylesheet">
</head>
<body>
{% block navbar %}

{% endblock %}
<div class="container">
    {% block contenido %}
    {% endblock %}
</div>
<script src="{% static 'bs522/bootstrap.bundle.min.js' %}"></script>
<script src="{% static 'fa/all.min.js' %}"></script>
</body>
</html>

usuarios/templates/usuarios/perfil_alumno.html
{% extends 'website/base_website.html' %}

{% block tittle_tab %}
    Mi perfil
{% endblock %}

{% block contenido %}
    <div class="row">
        <div class="col-">
            <h1>Mi Peril </h1>
            <form method="post">

                <div class="row">
                    <div class="col">
                        <label for="">Nombre</label>
                        <input type="text" class="form-control">
                    </div>

                    <div class="col">
                        <label for="">Apellidos</label>
                        <input type="text" class="form-control">
                    </div>
                    <div class="col">
                        <label for="">telefono</label>
                        <input type="tel" class="form-control">
                    </div>

                    <div class="col">
                        <label for="">Correo</label>
                        <input type="email" class="form-control">
                    </div>
                    <div class="col">
                        <input type="submit" class="btn btn-primary">
                    </div>
                </div>

            </form>
            <a href="#">Cambiar contraseña</a>
        </div>
    </div>
{% endblock %}

website/templates/website/base_website.html
{% extends 'base.html' %}

{% block navbar %}
{% include 'website/navbar.html' %}
{% endblock %}

website/templates/website/contacto.html
{% extends 'website/base_website.html' %}

{% block tittle_tab %}
    Contacto
{% endblock %}
{% block contenido %}
    <div class="row">
        <div class="col">
            <h1>Contactanos</h1>
            <form action="">
                <label for="">Correo Electronico</label>
                <input type="email" class="form-control">
                <label for="">Mensaje</label>
                <textarea name="" id="" cols="30" rows="10" class="form-control"></textarea>
                <input type="submit" class="btn btn-primary">
            </form>
        </div>
    </div>
{% endblock %}

website/templates/website/detalle_curso.html
{% extends 'website/base_website.html' %}

{% block tittle_tab %}
    Python Basico - CURSOS
{% endblock %}

{% block contenido %}
    <div class="row py-5">
        <div class="col">
            <h1>Cursos activos</h1>
        </div>
    </div>
    <div class="row">
        <div class="col">
            <h1>Python Basico</h1>
            <p>Abierto</p>
            <p>Programación</p>
            <img src="https://via.placeholder.com/250x200" class="img-fluid" alt="...">
            <p>Gustavo Jimenez</p>
            <p>$450</p>
            <p>
                Lorem ipsum dolor sit amet, consectetur adipisicing elit. Adipisci alias asperiores aspernatur at
                corporis facere fugiat maxime minima odit quaerat recusandae repellat sunt suscipit vitae, voluptatem.
                Dolorum labore libero praesentium!
            </p>
            <p>

                Lorem ipsum dolor sit amet, consectetur adipisicing elit. Harum id officia perspiciatis quis vero?
                Architecto assumenda consequatur dolor dolorum ducimus eius eos fugiat, illum laborum maxime mollitia,
                officiis repellendus voluptatem.
            </p>
            <a href="{% url 'website:inscripcion_curso' %}" class="btn btn-primary">Inscribirme</a>
        </div>
    </div>
{% endblock %}

website/templates/website/index.html
{% extends 'website/base_website.html' %}

{% block tittle_tab %}
    Inicio
{% endblock %}

{% block contenido %}
    <div class="row py-5">
        {% if request.user.is_authenticated %}
            <div class="col">
                <p>Hola {{ request.user }}</p>
            </div>
        {% endif %}
    </div>
    <div class="row">
        <div class="col">
            <h1>Cursos activos</h1>
        </div>
    </div>
    <div class="row">
        <div class="col">
            <div class="card" style="width: 18rem;">
                <img src="https://via.placeholder.com/150x100" class="card-img-top" alt="...">
                <div class="card-body">
                    <h5 class="card-title">Python Basico</h5>
                    <p class="card-text">Gustavo Jimenez</p>
                    <p class="card-text">$450</p>
                    <a href="{% url 'website:detalle_curso' 254 %}" class="btn btn-primary">Detalles</a>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

website/templates/website/inscripcion_curso.html
{% extends 'website/base_website.html' %}

{% block tittle_tab %}
    Inscripcion Python Basico - CURSOS
{% endblock %}

{% block contenido %}
    <div class="row py-5">
        <div class="col">
            <h1>Cursos activos</h1>
        </div>
    </div>
    <div class="row">
        <div class="col">
            <form action="">
                <table class="table">
                    {{ form.as_table }}
                    <tr>
                        <td colspan="2">
                            <input type="submit" class="btn btn-outline-primary">
                        </td>
                    </tr>
                </table>
            </form>
        </div>
    </div>
{% endblock %}

website/templates/website/navbar.html
<nav class="navbar navbar-expand-lg bg-light">
    <div class="container-fluid">
        <a class="navbar-brand" href="#">Cursos</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link" aria-current="page" href="{% url 'website:index'%}">Inicio</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                       aria-expanded="false">
                        Categorias
                    </a>
                    <ul class="dropdown-menu">
                        <li><a class="dropdown-item" href="#">Action</a></li>
                        <li><a class="dropdown-item" href="#">Another action</a></li>
                        <li>
                            <hr class="dropdown-divider">
                        </li>
                        <li><a class="dropdown-item" href="#">Something else here</a></li>
                    </ul>
                </li>
                <li class="nav-item">
                    <a class="nav-link " aria-current="page" href="{% url 'website:quienes_somos' %}">¿Quienes somos?</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link " aria-current="page" href="{% url 'website:contacto' %}">Contacto</a>
                </li>
            </ul>
            <form class="d-flex" role="search">
                <input class="form-control me-2" type="search" placeholder="Buscar Cursos" aria-label="Search">
                <button class="btn btn-outline-success me-2" type="submit">Buscar</button>
            </form>
            {% if request.user.is_authenticated %}
                <a class="btn btn-primary me-0" href="{% url 'usuarios:perfil_alumno' %}"">Mi Perfil</a>
                <a class="btn btn-primary me-0" href="{% url 'logout' %}"">Salir</a>
            {% else %}
                <a class="btn btn-primary me-2" href="{% url 'login' %}"">Iniciar Sesion</a>
                <a class="btn btn-outline-primary me-2" href="{% url 'website:registro_alumno' %}">Registrarse</a>

            {% endif %}


        </div>
    </div>
</nav>

website/templates/website/quienes_somos.html
{% extends 'website/base_website.html' %}

{% block tittle_tab %}
    Quienes somos
{% endblock %}
{% block contenido %}
    <div class="row">
        <div class="col">
            <h1>Quienes somos</h1>
            <img src="https://via.placeholder.com/800x300" alt="">
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusamus aspernatur dignissimos in iusto odio
                recusandae rem, tempora totam! Non, sunt, veniam? Asperiores fugit iste itaque molestias officia
                possimus qui! Excepturi!
                Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusamus aspernatur dignissimos in iusto odio
                recusandae rem, tempora totam! Non, sunt, veniam? Asperiores fugit iste itaque molestias officia
                possimus qui! Excepturi!
                Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusamus aspernatur dignissimos in iusto odio
                recusandae rem, tempora totam! Non, sunt, veniam? Asperiores fugit iste itaque molestias officia
                possimus qui! Excepturi!
                Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusamus aspernatur dignissimos in iusto odio
                recusandae rem, tempora totam! Non, sunt, veniam? Asperiores fugit iste itaque molestias officia
                possimus qui! Excepturi!
                Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusamus aspernatur dignissimos in iusto odio
                recusandae rem, tempora totam! Non, sunt, veniam? Asperiores fugit iste itaque molestias officia
                possimus qui! Excepturi!
                Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusamus aspernatur dignissimos in iusto odio
                recusandae rem, tempora totam! Non, sunt, veniam? Asperiores fugit iste itaque molestias officia
                possimus qui! Excepturi!Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusamus aspernatur
                dignissimos in iusto odio
                recusandae rem, tempora totam! Non, sunt, veniam? Asperiores fugit iste itaque molestias officia
                possimus qui! Excepturi!Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusamus aspernatur
                dignissimos in iusto odio
                recusandae rem, tempora totam! Non, sunt, veniam? Asperiores fugit iste itaque molestias officia
                possimus qui! Excepturi!Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusamus aspernatur
                dignissimos in iusto odio
                recusandae rem, tempora totam! Non, sunt, veniam? Asperiores fugit iste itaque molestias officia
                possimus qui! Excepturi!


            </p>
        </div>
    </div>
{% endblock %}